# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: GalliumOS Blog
email: hello@galliumos.org
description: The GalliumOS blog is where the GalliumOS team posts updates and news about the operating system, as well as other useful information we feel like our users should know.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.galliumos.org" # the base hostname & protocol for your site
twitter_username: GalliumOS
github_username:  GalliumOS

# Build settings
markdown: kramdown
permalink: /:year/:month/:title
kramdown:
  input: GFM
